/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'giorgio' at '12/20/15 9:58 AM' with Gradle 2.6
 *
 * @author giorgio, @date 12/20/15 9:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
